baseURL: https://goose.sh
languageCode: en
title: Goose in the Shell
theme: "blowfish"


caches:
  images:
    dir: :cacheDir/images


outputs:
  home:
    - HTML
    - RSS
    - JSON


taxonomies:
  tag: tags

menu:
  main:
    # - identifier: projects
    #   name: Projects
    #   url: /projects/
    #   weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: tools
      name: Tools
      url: /tools/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40

params:
  # OpenGraph
  description: "Goose in the Shell: Microelectronics Blog"
  # static
  images:
    - "images/og/goose-in-the-shell.png"
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#enhanced-seo

  copyright: "Â© 2025 Ilia N"

  enableRobotsTXT: true

  colorScheme: slate
  enableSearch: false


  author:
    name: Ilia
    # assets
    image: images/goose.png
    headline: "Microelectronics Enthusiast"
    bio: "Microelectronics Enthusiast | SWE at Meta working on AI ASICs"
    links:
      - github: https://github.com/inn-goose

  homepage:
    layout: hero
    homepageImage: images/city-day.png
    # disableHeroImageFilter: true
    showRecent: true
    showSummary: true

  footer:
    showScrollToTop: false

  mainSections: ["projects", "blog"]

  list:
    showHero: true
    showSummary: true

  article:
    showDateOnlyInArticle: true
    showAuthorBottom: true
    showPagination: false
    showTaxonomies: true
    showZenMode: true